version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    restart: always
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    networks:
      - local
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - local:/var/lib/mysql
    networks:
      - local

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  local:
    driver: local
